name: pokepocket

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: backend.Dockerfile
      # target: base
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /usr/api/src
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
    ports:
      - 3333:3333
    depends_on:
      - db
      - backend-setup
    restart: always
    env_file:
      - ./backend/.env
  db:
    container_name: db
    hostname: postgres
    image: postgres:latest
    ports:
      - 5743:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 8s
      retries: 5
    restart: always
    volumes:
      - db-data:/etc/data
    env_file:
      - ./backend/.env
  backend-setup:
    container_name: backend-setup
    build:
      context: .
      dockerfile: backend.Dockerfile
      target: base
    command: ["sh", "-c", "npm run migrate && npm run seed"]
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
volumes:
  db-data:
